name = "Havoc"
prefix = "havoc"
author = "havoc"
template = "cba"
mainprefix = "z"
folder_optionals = true

files = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "extras/addons",
    "extras/keys",
    "AUTHORS.txt",
    "havocl1512x.paa",
    "havocsl1512x.paa",
    "havocl12048.paa"
    ]

exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"
key_name = "{{prefix}}_{{version}}"


releasebuild = [
    "@zip havoc_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}",
    "!version_unset"
]

[header_exts]
version = "{{git \"id 8\"}}"
