#include "script_component.hpp"

class CfgPatches {
  class ADDON {
    name = COMPONENT_NAME;
    author = QAUTHOR;
        units[] = {
          QGVAR(Item_PlateCarrier2_brncizek),
          QGVAR(Item_PlateCarrier2_brnyonv),
          QGVAR(Item_PlateCarrier2_blkyonv),
          QGVAR(Item_PlateCarrier2_brnmidas),
          QGVAR(Item_PlateCarrier1_Blackslv),
          QGVAR(Item_PlateCarrier1_Greenslv),
          QGVAR(Item_PlateCarrier1_Coyoteslv),
          QGVAR(Item_PlateCarrier1_Khakislv),
          QGVAR(Item_PlateCarrier1_MARPATslv),
          QGVAR(Item_PlateCarrier1_Blackblk),
          QGVAR(Item_PlateCarrier1_Greenblk),
          QGVAR(Item_PlateCarrier1_Coyoteblk),
          QGVAR(Item_PlateCarrier1_Khakiblk),
          QGVAR(Item_PlateCarrier1_MARPATblk),
          QGVAR(Item_PlateCarrier1_Blackblu),
          QGVAR(Item_PlateCarrier1_Greenblu),
          QGVAR(Item_PlateCarrier1_Coyoteblu),
          QGVAR(Item_PlateCarrier1_Khakiblu),
          QGVAR(Item_PlateCarrier1_MARPATblu),
          QGVAR(Item_PlateCarrier1_Blackcmd),
          QGVAR(Item_PlateCarrier1_Greencmd),
          QGVAR(Item_PlateCarrier1_Coyotecmd),
          QGVAR(Item_PlateCarrier1_Khakicmd),
          QGVAR(Item_PlateCarrier1_MARPATcmd),
          QGVAR(Item_PlateCarrier1_Blackgld),
          QGVAR(Item_PlateCarrier1_Greengld),
          QGVAR(Item_PlateCarrier1_Coyotegld),
          QGVAR(Item_PlateCarrier1_Khakigld),
          QGVAR(Item_PlateCarrier1_MARPATgld),
          QGVAR(Item_PlateCarrier1_Blackgrn),
          QGVAR(Item_PlateCarrier1_Greengrn),
          QGVAR(Item_PlateCarrier1_Coyotegrn),
          QGVAR(Item_PlateCarrier1_Khakigrn),
          QGVAR(Item_PlateCarrier1_MARPATgrn),
          QGVAR(Item_PlateCarrier1_Blackgry),
          QGVAR(Item_PlateCarrier1_Greengry),
          QGVAR(Item_PlateCarrier1_Coyotegry),
          QGVAR(Item_PlateCarrier1_Khakigry),
          QGVAR(Item_PlateCarrier1_MARPATgry),
          QGVAR(Item_PlateCarrier1_Blackred),
          QGVAR(Item_PlateCarrier1_Greenred),
          QGVAR(Item_PlateCarrier1_Coyotered),
          QGVAR(Item_PlateCarrier1_Khakired),
          QGVAR(Item_PlateCarrier1_MARPATred),
          QGVAR(Item_PlateCarrier1_Blackblk),
          QGVAR(Item_PlateCarrier1_Greenblk),
          QGVAR(Item_PlateCarrier1_Coyoteblk),
          QGVAR(Item_PlateCarrier1_Khakiblk),
          QGVAR(Item_PlateCarrier1_MARPATblk),
          QGVAR(Item_PlateCarrier2_Blackslv),
          QGVAR(Item_PlateCarrier2_Greenslv),
          QGVAR(Item_PlateCarrier2_Coyoteslv),
          QGVAR(Item_PlateCarrier2_Khakislv),
          QGVAR(Item_PlateCarrier2_MARPATslv),
          QGVAR(Item_PlateCarrier2_Blackblk),
          QGVAR(Item_PlateCarrier2_Greenblk),
          QGVAR(Item_PlateCarrier2_Coyoteblk),
          QGVAR(Item_PlateCarrier2_Khakiblk),
          QGVAR(Item_PlateCarrier2_MARPATblk),
          QGVAR(Item_PlateCarrier2_Blackblu),
          QGVAR(Item_PlateCarrier2_Greenblu),
          QGVAR(Item_PlateCarrier2_Coyoteblu),
          QGVAR(Item_PlateCarrier2_Khakiblu),
          QGVAR(Item_PlateCarrier2_MARPATblu),
          QGVAR(Item_PlateCarrier2_Blackcmd),
          QGVAR(Item_PlateCarrier2_Greencmd),
          QGVAR(Item_PlateCarrier2_Coyotecmd),
          QGVAR(Item_PlateCarrier2_Khakicmd),
          QGVAR(Item_PlateCarrier2_MARPATcmd),
          QGVAR(Item_PlateCarrier2_Blackgld),
          QGVAR(Item_PlateCarrier2_Greengld),
          QGVAR(Item_PlateCarrier2_Coyotegld),
          QGVAR(Item_PlateCarrier2_Khakigld),
          QGVAR(Item_PlateCarrier2_MARPATgld),
          QGVAR(Item_PlateCarrier2_Blackgrn),
          QGVAR(Item_PlateCarrier2_Greengrn),
          QGVAR(Item_PlateCarrier2_Coyotegrn),
          QGVAR(Item_PlateCarrier2_Khakigrn),
          QGVAR(Item_PlateCarrier2_MARPATgrn),
          QGVAR(Item_PlateCarrier2_Blackgry),
          QGVAR(Item_PlateCarrier2_Greengry),
          QGVAR(Item_PlateCarrier2_Coyotegry),
          QGVAR(Item_PlateCarrier2_Khakigry),
          QGVAR(Item_PlateCarrier2_MARPATgry),
          QGVAR(Item_PlateCarrier2_Blackred),
          QGVAR(Item_PlateCarrier2_Greenred),
          QGVAR(Item_PlateCarrier2_Coyotered),
          QGVAR(Item_PlateCarrier2_Khakired),
          QGVAR(Item_PlateCarrier2_MARPATred),
          QGVAR(Item_PlateCarrier2_Blackblk),
          QGVAR(Item_PlateCarrier2_Greenblk),
          QGVAR(Item_PlateCarrier2_Coyoteblk),
          QGVAR(Item_PlateCarrier2_Khakiblk),
          QGVAR(Item_PlateCarrier2_MARPATblk),
          QGVAR(Item_PlateCarrier1_brnslv),
          QGVAR(Item_PlateCarrier2_brnslv),
          QGVAR(Item_PlateCarrierHeavy_Blackslv),
          QGVAR(Item_PlateCarrierHeavy_Coyoteslv),
          QGVAR(Item_PlateCarrierHeavy_Greenslv),
          QGVAR(Item_PlateCarrier1_brnblk),
          QGVAR(Item_PlateCarrier2_brnblk),
          QGVAR(Item_PlateCarrierHeavy_Blackblk),
          QGVAR(Item_PlateCarrierHeavy_Coyoteblk),
          QGVAR(Item_PlateCarrierHeavy_Greenblk),
          QGVAR(Item_PlateCarrier1_brnblu),
          QGVAR(Item_PlateCarrier2_brnblu),
          QGVAR(Item_PlateCarrierHeavy_Blackblu),
          QGVAR(Item_PlateCarrierHeavy_Coyoteblu),
          QGVAR(Item_PlateCarrierHeavy_Greenblu),
          QGVAR(Item_PlateCarrier1_brncmd),
          QGVAR(Item_PlateCarrier2_brncmd),
          QGVAR(Item_PlateCarrierHeavy_Blackcmd),
          QGVAR(Item_PlateCarrierHeavy_Coyotecmd),
          QGVAR(Item_PlateCarrierHeavy_Greencmd),
          QGVAR(Item_PlateCarrier1_brngld),
          QGVAR(Item_PlateCarrier2_brngld),
          QGVAR(Item_PlateCarrierHeavy_Blackgld),
          QGVAR(Item_PlateCarrierHeavy_Coyotegld),
          QGVAR(Item_PlateCarrierHeavy_Greengld),
          QGVAR(Item_PlateCarrier1_brngrn),
          QGVAR(Item_PlateCarrier2_brngrn),
          QGVAR(Item_PlateCarrierHeavy_Blackgrn),
          QGVAR(Item_PlateCarrierHeavy_Coyotegrn),
          QGVAR(Item_PlateCarrierHeavy_Greengrn),
          QGVAR(Item_PlateCarrier1_brngry),
          QGVAR(Item_PlateCarrier2_brngry),
          QGVAR(Item_PlateCarrierHeavy_Blackgry),
          QGVAR(Item_PlateCarrierHeavy_Coyotegry),
          QGVAR(Item_PlateCarrierHeavy_Greengry),
          QGVAR(Item_PlateCarrier1_brnred),
          QGVAR(Item_PlateCarrier2_brnred),
          QGVAR(Item_PlateCarrierHeavy_Blackred),
          QGVAR(Item_PlateCarrierHeavy_Coyotered),
          QGVAR(Item_PlateCarrierHeavy_Greenred),
          QGVAR(Item_PlateCarrier1_brnblk),
          QGVAR(Item_PlateCarrier2_brnblk),
          QGVAR(Item_PlateCarrierHeavy_Blackblk),
          QGVAR(Item_PlateCarrierHeavy_Coyoteblk),
          QGVAR(Item_PlateCarrierHeavy_Greenblk)
        };
        weapons[] = {
          QGVAR(PlateCarrier2_brncizek),
          QGVAR(PlateCarrier2_brnyonv),
          QGVAR(PlateCarrier2_blkyonv),
          QGVAR(PlateCarrier2_brnmidas),
          QGVAR(PlateCarrier1_Blackslv),
          QGVAR(PlateCarrier1_Greenslv),
          QGVAR(PlateCarrier1_Coyoteslv),
          QGVAR(PlateCarrier1_Khakislv),
          QGVAR(PlateCarrier1_MARPATslv),
          QGVAR(PlateCarrier1_Blackblk),
          QGVAR(PlateCarrier1_Greenblk),
          QGVAR(PlateCarrier1_Coyoteblk),
          QGVAR(PlateCarrier1_Khakiblk),
          QGVAR(PlateCarrier1_MARPATblk),
          QGVAR(PlateCarrier1_Blackblu),
          QGVAR(PlateCarrier1_Greenblu),
          QGVAR(PlateCarrier1_Coyoteblu),
          QGVAR(PlateCarrier1_Khakiblu),
          QGVAR(PlateCarrier1_MARPATblu),
          QGVAR(PlateCarrier1_Blackcmd),
          QGVAR(PlateCarrier1_Greencmd),
          QGVAR(PlateCarrier1_Coyotecmd),
          QGVAR(PlateCarrier1_Khakicmd),
          QGVAR(PlateCarrier1_MARPATcmd),
          QGVAR(PlateCarrier1_Blackgld),
          QGVAR(PlateCarrier1_Greengld),
          QGVAR(PlateCarrier1_Coyotegld),
          QGVAR(PlateCarrier1_Khakigld),
          QGVAR(PlateCarrier1_MARPATgld),
          QGVAR(PlateCarrier1_Blackgrn),
          QGVAR(PlateCarrier1_Greengrn),
          QGVAR(PlateCarrier1_Coyotegrn),
          QGVAR(PlateCarrier1_Khakigrn),
          QGVAR(PlateCarrier1_MARPATgrn),
          QGVAR(PlateCarrier1_Blackgry),
          QGVAR(PlateCarrier1_Greengry),
          QGVAR(PlateCarrier1_Coyotegry),
          QGVAR(PlateCarrier1_Khakigry),
          QGVAR(PlateCarrier1_MARPATgry),
          QGVAR(PlateCarrier1_Blackred),
          QGVAR(PlateCarrier1_Greenred),
          QGVAR(PlateCarrier1_Coyotered),
          QGVAR(PlateCarrier1_Khakired),
          QGVAR(PlateCarrier1_MARPATred),
          QGVAR(PlateCarrier1_Blackblk),
          QGVAR(PlateCarrier1_Greenblk),
          QGVAR(PlateCarrier1_Coyoteblk),
          QGVAR(PlateCarrier1_Khakiblk),
          QGVAR(PlateCarrier1_MARPATblk),
          QGVAR(PlateCarrier2_Blackslv),
          QGVAR(PlateCarrier2_Greenslv),
          QGVAR(PlateCarrier2_Coyoteslv),
          QGVAR(PlateCarrier2_Khakislv),
          QGVAR(PlateCarrier2_MARPATslv),
          QGVAR(PlateCarrier2_Blackblk),
          QGVAR(PlateCarrier2_Greenblk),
          QGVAR(PlateCarrier2_Coyoteblk),
          QGVAR(PlateCarrier2_Khakiblk),
          QGVAR(PlateCarrier2_MARPATblk),
          QGVAR(PlateCarrier2_Blackblu),
          QGVAR(PlateCarrier2_Greenblu),
          QGVAR(PlateCarrier2_Coyoteblu),
          QGVAR(PlateCarrier2_Khakiblu),
          QGVAR(PlateCarrier2_MARPATblu),
          QGVAR(PlateCarrier2_Blackcmd),
          QGVAR(PlateCarrier2_Greencmd),
          QGVAR(PlateCarrier2_Coyotecmd),
          QGVAR(PlateCarrier2_Khakicmd),
          QGVAR(PlateCarrier2_MARPATcmd),
          QGVAR(PlateCarrier2_Blackgld),
          QGVAR(PlateCarrier2_Greengld),
          QGVAR(PlateCarrier2_Coyotegld),
          QGVAR(PlateCarrier2_Khakigld),
          QGVAR(PlateCarrier2_MARPATgld),
          QGVAR(PlateCarrier2_Blackgrn),
          QGVAR(PlateCarrier2_Greengrn),
          QGVAR(PlateCarrier2_Coyotegrn),
          QGVAR(PlateCarrier2_Khakigrn),
          QGVAR(PlateCarrier2_MARPATgrn),
          QGVAR(PlateCarrier2_Blackgry),
          QGVAR(PlateCarrier2_Greengry),
          QGVAR(PlateCarrier2_Coyotegry),
          QGVAR(PlateCarrier2_Khakigry),
          QGVAR(PlateCarrier2_MARPATgry),
          QGVAR(PlateCarrier2_Blackred),
          QGVAR(PlateCarrier2_Greenred),
          QGVAR(PlateCarrier2_Coyotered),
          QGVAR(PlateCarrier2_Khakired),
          QGVAR(PlateCarrier2_MARPATred),
          QGVAR(PlateCarrier2_Blackblk),
          QGVAR(PlateCarrier2_Greenblk),
          QGVAR(PlateCarrier2_Coyoteblk),
          QGVAR(PlateCarrier2_Khakiblk),
          QGVAR(PlateCarrier2_MARPATblk),
          QGVAR(PlateCarrier1_brnslv),
          QGVAR(PlateCarrier2_brnslv),
          QGVAR(PlateCarrierHeavy_Blackslv),
          QGVAR(PlateCarrierHeavy_Coyoteslv),
          QGVAR(PlateCarrierHeavy_Greenslv),
          QGVAR(PlateCarrier1_brnblk),
          QGVAR(PlateCarrier2_brnblk),
          QGVAR(PlateCarrierHeavy_Blackblk),
          QGVAR(PlateCarrierHeavy_Coyoteblk),
          QGVAR(PlateCarrierHeavy_Greenblk),
          QGVAR(PlateCarrier1_brnblu),
          QGVAR(PlateCarrier2_brnblu),
          QGVAR(PlateCarrierHeavy_Blackblu),
          QGVAR(PlateCarrierHeavy_Coyoteblu),
          QGVAR(PlateCarrierHeavy_Greenblu),
          QGVAR(PlateCarrier1_brncmd),
          QGVAR(PlateCarrier2_brncmd),
          QGVAR(PlateCarrierHeavy_Blackcmd),
          QGVAR(PlateCarrierHeavy_Coyotecmd),
          QGVAR(PlateCarrierHeavy_Greencmd),
          QGVAR(PlateCarrier1_brngld),
          QGVAR(PlateCarrier2_brngld),
          QGVAR(PlateCarrierHeavy_Blackgld),
          QGVAR(PlateCarrierHeavy_Coyotegld),
          QGVAR(PlateCarrierHeavy_Greengld),
          QGVAR(PlateCarrier1_brngrn),
          QGVAR(PlateCarrier2_brngrn),
          QGVAR(PlateCarrierHeavy_Blackgrn),
          QGVAR(PlateCarrierHeavy_Coyotegrn),
          QGVAR(PlateCarrierHeavy_Greengrn),
          QGVAR(PlateCarrier1_brngry),
          QGVAR(PlateCarrier2_brngry),
          QGVAR(PlateCarrierHeavy_Blackgry),
          QGVAR(PlateCarrierHeavy_Coyotegry),
          QGVAR(PlateCarrierHeavy_Greengry),
          QGVAR(PlateCarrier1_brnred),
          QGVAR(PlateCarrier2_brnred),
          QGVAR(PlateCarrierHeavy_Blackred),
          QGVAR(PlateCarrierHeavy_Coyotered),
          QGVAR(PlateCarrierHeavy_Greenred),
          QGVAR(PlateCarrier1_brnblk),
          QGVAR(PlateCarrier2_brnblk),
          QGVAR(PlateCarrierHeavy_Blackblk),
          QGVAR(PlateCarrierHeavy_Coyoteblk),
          QGVAR(PlateCarrierHeavy_Greenblk)  
        };
        requiredVersion = 0.1;
        requiredAddons[] = {"A3_Characters_F"};
    };
};

class CfgVehicles {
  class B_soldier_F;
  class B_Sniper_F;
  class Item_Base_F;
  class Vest_Base_F;

  #include "CfgVehicles_demo.hpp"
  #include "CfgVehicles_cmd.hpp"
  #include "CfgVehicles_blu.hpp"
  #include "CfgVehicles_blk.hpp"
  #include "CfgVehicles_red.hpp"
  #include "CfgVehicles_gry.hpp"
  #include "CfgVehicles_grn.hpp"
  #include "CfgVehicles_gld.hpp"
  #include "CfgVehicles_slv.hpp"
};

class CfgWeapons {
  class InventoryItem_Base_F;
  class ItemCore;
  class Vest_Camo_Base;
  class Vest_NoCamo_Base;
  class VestItem;
  class V_PlateCarrierGL_rgr: Vest_NoCamo_Base {
      class ItemInfo;
  };
  class V_TacVest_khk;
  class V_PlateCarrierIA1_dgtl: Vest_NoCamo_Base {
      class ItemInfo;
  };
  class V_PlateCarrier1_rgr: Vest_NoCamo_Base {
      class ItemInfo;
  };
  class V_PlateCarrier2_rgr: V_PlateCarrier1_rgr {
  class ItemInfo;
  };
  #include "CfgWeapons_demo.hpp"
  #include "CfgWeapons_cmd.hpp"
  #include "CfgWeapons_blu.hpp"
  #include "CfgWeapons_blk.hpp"
  #include "CfgWeapons_red.hpp"
  #include "CfgWeapons_gry.hpp"
  #include "CfgWeapons_grn.hpp"
  #include "CfgWeapons_gld.hpp"
  #include "CfgWeapons_slv.hpp"
};
